/**
 * 校园机会雷达 - 模拟校园信息数据
 * 数据来源：计算机协会软件部 2026 年秋季纳新第二轮考核题目（共 26 条模拟信息）
 * 原则：不编造题目未提供的信息；缺失/不确定的信息以 notices 显式标注。
 */

// 考核题目要求：以 2026 年 9 月 19 日考核当日为时间背景。
// 因此产品内置"时间锚点"，所有状态（进行中/已截止/倒计时）均相对该时间计算，保证演示与评审时状态稳定。
window.TIME_ANCHOR = new Date('2026-09-19T14:00:00+08:00');

window.ACTIVITY_TYPES = ['竞赛', '讲座分享', '招募', '学习成长', '志愿服务', '校园活动', '学生发起', '重要通知', '学习资料'];

window.ACTIVITIES = [
  {
    id: 1,
    title: '“蓝桥杯”程序设计校内训练营',
    type: '学习成长',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '原计划 9月20日起 每周六 19:00 训练',
    timeStart: '2026-09-20T19:00',
    timeEnd: null,
    deadline: '2026-09-24T22:00',
    deadlineText: '9月24日 22:00 报名截止',
    location: '',
    audience: '面向全校学生',
    desc: '9月24日22:00报名截止；原计划9月20日起每周六19:00训练；面向全校学生；零基础可参加。',
    tags: ['零基础可参加'],
    freshman: true,
    updates: [
      { fromId: 9, note: '最新通知：首次训练调整为 9月21日 19:30，地点改至实验楼A402；已报名同学无需重复提交，报名截止时间不变。' }
    ],
    notices: [],
    risk: null
  },
  {
    id: 2,
    title: 'AI应用入门公开课',
    type: '讲座分享',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月19日 19:00，预计90分钟',
    timeStart: '2026-09-19T19:00',
    timeEnd: null,
    deadline: null,
    deadlineText: '无需报名',
    location: '计算机学院教学楼',
    audience: '面向全校学生',
    desc: '9月19日19:00；计算机学院教学楼；面向全校学生；无需报名；预计90分钟。',
    tags: ['无需报名'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 3,
    title: '大学生创新创业项目团队招募',
    type: '招募',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '每周需稳定投入 4 小时以上',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-09-22T18:00',
    deadlineText: '9月22日 18:00 截止',
    location: '',
    audience: '需提交简短自我介绍',
    desc: '招募开发、设计、材料成员；每周需稳定投入4小时以上；9月22日18:00截止；需提交简短自我介绍。',
    tags: ['项目制'],
    freshman: true,
    updates: [
      { fromId: 20, note: '补充说明：开发方向名额已满，现主要补充设计与材料成员；此前已投递者无需重复提交。' }
    ],
    notices: [],
    risk: null
  },
  {
    id: 4,
    title: '数学建模竞赛经验分享会',
    type: '讲座分享',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '直播已于 9月18日 19:30 结束',
    timeStart: '2026-09-18T19:30',
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '线上直播',
    audience: '不限专业',
    desc: '直播时间为9月18日19:30；不限专业；直播已结束，活动方预计9月20日上传回放。',
    tags: ['有回放'],
    freshman: true,
    updates: [],
    notices: ['直播已结束，回放预计 9月20日 上传，届时可再关注更新。'],
    risk: null
  },
  {
    id: 5,
    title: '校园公益志愿服务活动',
    type: '志愿服务',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月27日 8:30—17:00，预计服务8小时',
    timeStart: '2026-09-27T08:30',
    timeEnd: '2026-09-27T17:00',
    deadline: '2026-09-20T12:00',
    deadlineText: '9月20日 12:00 报名截止',
    location: '',
    audience: '需提前到场签到',
    desc: '活动时间9月27日8:30—17:00；9月20日12:00报名截止；预计服务8小时；需提前到场签到。',
    tags: ['志愿服务'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 6,
    title: 'Web开发零基础学习小组',
    type: '学习成长',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月23日起 每周三 19:30，共6周',
    timeStart: '2026-09-23T19:30',
    timeEnd: null,
    deadline: null,
    deadlineText: '报名时间未注明，满员即止',
    location: '',
    audience: '面向零基础学生，限30人',
    desc: '9月23日起每周三19:30开展，共6周；面向零基础学生；限30人；报名时间未注明，满员即止。',
    tags: ['零基础可参加', '限30人'],
    freshman: true,
    updates: [],
    notices: ['报名时间未注明，满员即止，建议尽早联系报名。'],
    risk: null
  },
  {
    id: 7,
    title: 'AI创新应用挑战赛',
    type: '竞赛',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '10月20日 提交作品',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-09-21T18:00',
    deadlineText: '9月21日 18:00 前完成校内意向登记',
    location: '',
    audience: '2—4人组队',
    desc: '2—4人组队；9月21日18:00前完成校内意向登记；10月20日提交作品；意向登记不等同于最终作品提交。',
    tags: ['组队参赛'],
    freshman: true,
    updates: [],
    notices: ['意向登记不等同于最终作品提交，登记后仍需在 10月20日 前完成作品提交。'],
    risk: null
  },
  {
    id: 8,
    title: '校园软件项目组招募',
    type: '招募',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '每周预计投入 5 小时',
    timeStart: null,
    timeEnd: null,
    deadline: null,
    deadlineText: '长期招募，满员即止',
    location: '',
    audience: '面向大一、大二学生',
    desc: '开发校园实用工具；面向大一、大二学生；希望成员了解Git基本操作；每周预计投入5小时；长期招募，满员即止。',
    tags: ['长期招募', '需要Git基础'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 9,
    title: '程序设计训练营补充通知',
    type: '重要通知',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '首次训练调整为 9月21日 19:30',
    timeStart: '2026-09-21T19:30',
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '实验楼A402',
    audience: '已报名同学无需重复提交',
    desc: '因场地调整，首次训练改为9月21日19:30，地点改至实验楼A402；已报名同学无需重复提交；报名截止时间不变。',
    tags: ['时间地点变更'],
    freshman: true,
    updates: [],
    relatesTo: 1,
    notices: [],
    risk: null
  },
  {
    id: 10,
    title: '前端开发经验交流会',
    type: '讲座分享',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月19日 15:00—16:30',
    timeStart: '2026-09-19T15:00',
    timeEnd: '2026-09-19T16:30',
    deadline: null,
    deadlineText: '无需报名',
    location: '线下A201，同步线上直播',
    audience: '',
    desc: '9月19日15:00—16:30；线下A201并同步线上直播；无需报名。',
    tags: ['无需报名', '线上同步'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 11,
    title: '大学生科研入门分享会',
    type: '讲座分享',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月21日 19:00—20:30',
    timeStart: '2026-09-21T19:00',
    timeEnd: '2026-09-21T20:30',
    deadline: null,
    deadlineText: '',
    location: '',
    audience: '面向全校学生',
    desc: '9月21日19:00—20:30；介绍论文检索、学生科研项目和导师联系方法；面向全校学生。',
    tags: ['科研入门'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 12,
    title: '全国高校计算机能力挑战赛',
    type: '竞赛',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-10-05T23:59',
    deadlineText: '10月5日 23:59 报名截止',
    location: '',
    audience: '面向本科生，个人参赛',
    desc: '面向本科生；10月5日23:59报名截止；个人参赛；具体费用信息未提供。',
    tags: ['个人参赛'],
    freshman: true,
    updates: [],
    notices: ['具体费用信息未提供，报名前建议向主办方确认。'],
    risk: null
  },
  {
    id: 13,
    title: '科研助理招募',
    type: '招募',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '每周预计投入 6 小时',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-09-21T23:59',
    deadlineText: '9月21日 截止报名',
    location: '',
    audience: '仅限大二及以上学生',
    desc: '协助数据整理和实验工作；仅限大二及以上学生；每周预计投入6小时；9月21日截止报名。',
    tags: ['科研方向'],
    freshman: false,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 14,
    title: 'Git与GitHub零基础工作坊',
    type: '学习成长',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月21日 19:00—20:30',
    timeStart: '2026-09-21T19:00',
    timeEnd: '2026-09-21T20:30',
    deadline: null,
    deadlineText: '需提前预约',
    location: '',
    audience: '主要面向大一新生，限40人',
    desc: '9月21日19:00—20:30；主要面向大一新生；限40人；需提前预约，提交报名表不代表最终录取，以审核通知为准。',
    tags: ['零基础可参加', '限40人'],
    freshman: true,
    updates: [],
    notices: ['提交报名表不代表最终录取，以审核通知为准。'],
    risk: null
  },
  {
    id: 15,
    title: 'AI应用创意挑战',
    type: '竞赛',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月30日 前提交最终作品',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-09-23T23:59',
    deadlineText: '9月23日 23:59 前提交创意方案',
    location: '',
    audience: '允许个人或团队参加',
    desc: '9月23日23:59前提交创意方案；9月30日前提交最终作品；允许个人或团队参加；进入展示环节后可再组队。',
    tags: ['可个人参赛'],
    freshman: true,
    updates: [],
    notices: ['创意方案（9/23）与最终作品（9/30）为两个不同节点，注意区分。'],
    risk: null
  },
  {
    id: 16,
    title: '校园摄影志愿者招募',
    type: '志愿服务',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '长期招募',
    timeStart: null,
    timeEnd: null,
    deadline: null,
    deadlineText: '报名截止时间未注明',
    location: '',
    audience: '有摄影设备者优先但不作硬性要求',
    desc: '长期招募；参与校内大型活动摄影；具体报名截止时间未注明；有摄影设备者优先但不作硬性要求。',
    tags: ['长期招募'],
    freshman: true,
    updates: [],
    notices: ['具体报名截止时间未注明。'],
    risk: null
  },
  {
    id: 17,
    title: 'Python程序设计学习资料合集',
    type: '学习资料',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '资料长期开放',
    timeStart: null,
    timeEnd: null,
    deadline: null,
    deadlineText: '当前网盘提取信息有效至 9月22日',
    location: '',
    audience: '',
    desc: '包含课程、练习和项目案例；资料长期开放；当前网盘提取信息有效至9月22日，后续将统一更新。',
    tags: ['自学资料'],
    freshman: true,
    updates: [],
    notices: ['当前网盘提取信息有效至 9月22日，之后将统一更新，建议尽快保存。'],
    risk: null
  },
  {
    id: 18,
    title: '网络安全兴趣交流小组',
    type: '学习成长',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '首次交流 9月19日 19:30，之后每两周一次',
    timeStart: '2026-09-19T19:30',
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '',
    audience: '面向CTF、Web安全等方向感兴趣的学生，不限基础',
    desc: '首次交流时间为9月19日19:30；之后每两周开展一次；面向CTF、Web安全等方向感兴趣的学生；不限基础。',
    tags: ['不限基础'],
    freshman: true,
    updates: [],
    notices: [],
    risk: null
  },
  {
    id: 19,
    title: '学生创新项目路演观摩',
    type: '校园活动',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '9月20日 14:30',
    timeStart: '2026-09-20T14:30',
    timeEnd: null,
    deadline: '2026-09-18T22:00',
    deadlineText: '原报名已于 9月18日 22:00 截止',
    location: '',
    audience: '',
    desc: '活动时间9月20日14:30；原报名截止时间为9月18日22:00；活动方说明如现场仍有余位，可接受候补入场。',
    tags: ['可候补入场'],
    freshman: true,
    updates: [],
    notices: ['报名已截止；如现场仍有余位，可接受候补入场。'],
    risk: null
  },
  {
    id: 20,
    title: '创新创业项目团队补充说明',
    type: '重要通知',
    source: 'official',
    sourceLabel: '官方发布',
    timeText: '',
    timeStart: null,
    timeEnd: null,
    deadline: '2026-09-22T18:00',
    deadlineText: '9月22日 18:00 截止',
    location: '',
    audience: '',
    desc: '开发方向名额已满，现主要补充设计与材料成员；9月22日18:00截止；此前已投递者无需重复提交。',
    tags: ['招募方向调整'],
    freshman: true,
    updates: [],
    relatesTo: 3,
    notices: [],
    risk: null
  },
  {
    id: 21,
    title: '计算机学院AI产品设计分享会',
    type: '讲座分享',
    source: 'college',
    sourceLabel: '学院发布 · 计算机学院',
    timeText: '9月20日 19:00',
    timeStart: '2026-09-20T19:00',
    timeEnd: null,
    deadline: null,
    deadlineText: '无需报名，座位有限',
    location: '明德楼B203',
    audience: '面向全校学生',
    desc: '计算机学院发布；9月20日19:00；明德楼B203；面向全校学生；无需报名，座位有限。',
    tags: ['无需报名'],
    freshman: true,
    updates: [],
    notices: ['座位有限，建议提前到场。'],
    risk: null
  },
  {
    id: 22,
    title: '学生发起｜周末羽毛球约球',
    type: '学生发起',
    source: 'student',
    sourceLabel: '学生发布',
    timeText: '9月20日 16:00',
    timeStart: '2026-09-20T16:00',
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '场地待最终确认',
    audience: '计划6—8人，费用AA',
    desc: '学生个人发布；9月20日16:00；计划6—8人；费用AA；场地待最终确认。',
    tags: ['运动', '费用AA'],
    freshman: true,
    updates: [],
    notices: ['场地待最终确认，参与前请与发布者核实。'],
    risk: null
  },
  {
    id: 23,
    title: '学生发起｜AI工具交流搭子招募',
    type: '学生发起',
    source: 'student',
    sourceLabel: '学生发布',
    timeText: '拟于 9月21日 晚开展',
    timeStart: '2026-09-21T19:00',
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '具体地点未确定',
    audience: '欢迎零基础',
    desc: '学生个人发布；拟于9月21日晚开展；欢迎零基础；报名后拉群；具体地点未确定。',
    tags: ['零基础可参加'],
    freshman: true,
    updates: [],
    notices: ['具体地点未确定，报名后请留意群内通知。'],
    risk: null
  },
  {
    id: 24,
    title: '学生发起｜“校园兼职福利分享”',
    type: '学生发起',
    source: 'student',
    sourceLabel: '学生发布',
    timeText: '',
    timeStart: null,
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '未提供',
    audience: '',
    desc: '学生个人发布；称“零门槛、日结”，要求添加私人微信获取详情；未提供主办方、地点和完整内容。',
    tags: [],
    freshman: false,
    updates: [],
    notices: [],
    risk: {
      level: 'high',
      title: '该信息存在较高风险，请谨慎对待',
      reasons: [
        '要求添加私人微信才能获取详情，脱离平台沟通',
        '未提供主办方、地点和完整活动内容',
        '“零门槛、日结”是常见引流话术'
      ]
    }
  },
  {
    id: 25,
    title: '学生发起｜数码新品体验交流',
    type: '学生发起',
    source: 'student',
    sourceLabel: '学生发布',
    timeText: '活动时间、地点未注明',
    timeStart: null,
    timeEnd: null,
    deadline: null,
    deadlineText: '',
    location: '未注明',
    audience: '',
    desc: '学生个人发布；标题为技术交流，正文主要介绍某商家优惠及购买链接；活动时间、地点未注明。',
    tags: [],
    freshman: false,
    updates: [],
    notices: [],
    risk: {
      level: 'mid',
      title: '疑似商业推广内容',
      reasons: [
        '标题标注为技术交流，正文却主要是商家优惠与购买链接',
        '活动时间、地点均未注明，无法核实真实性'
      ]
    }
  },
  {
    id: 26,
    title: '外国语学院校园语言角',
    type: '校园活动',
    source: 'college',
    sourceLabel: '学院发布 · 外国语学院',
    timeText: '9月21日 15:00',
    timeStart: '2026-09-21T15:00',
    timeEnd: null,
    deadline: null,
    deadlineText: '无需提前报名',
    location: '',
    audience: '面向全校学生',
    desc: '外国语学院发布；9月21日15:00；面向全校学生；自由交流；场地容量有限，无需提前报名。',
    tags: ['无需报名', '自由交流'],
    freshman: true,
    updates: [],
    notices: ['场地容量有限，建议提前到场。'],
    risk: null
  }
];
